---
- name: Get Azure Data
  hosts: localhost
  gather_facts: no

  vars:
    snow_details:
      host: "https://dev181367.service-now.com"
      username: "admin"
      password: "vz*=hwF1CY5G"
    resource_group: "rg-ww-ce-automation-development-kcl-eastus-001"

  tasks:

  - name: Gather Azure Data
    include_tasks: tasks/get_azure_resources.yml

  - name: Update SNOW
    include_tasks: tasks/cmdb_add_or_update.yml
