---
- name: Get Azure Data
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Gather Azure Data
    include_tasks: tasks/get_azure_resources.yml

  - name: Save the Azure data for use in later plays
    set_fact: 
      all_machine_sizes: "{{all_machine_sizes}}"

- name: Add a CI to the SNOW CMDB
  hosts: all
  gather_facts: no

  vars:
    snow_details:
      host: "https://dev181367.service-now.com"
      username: "admin"
      password: "vz*=hwF1CY5G"

  tasks:
  - name: Update SNOW
    include_tasks: tasks/cmdb_add_or_update.yml

