---
- name: Add a CI to the SNOW CMDB
  hosts: localhost
  gather_facts: no

  vars:
    resource_group: "rg-ww-ce-automation-development-kcl-eastus-001"
    snow_details:
      host: "https://dev181367.service-now.com"
      username: "admin"
      password: "vz*=hwF1CY5G"

  tasks:
  - name: Gather Azure Data
    include_tasks: tasks/get_azure_resources.yml

  - name: Update SNOW
    include_tasks: tasks/cmdb_add_or_update.yml
    loop: "{{all_azure_rg_resources.vms | list}}"

