---
- name: Get Azure Data
  hosts: all
  gather_facts: yes

  vars:
    snow_details:
      host: "https://dev181367.service-now.com"
      username: "admin"
      password: "vz*=hwF1CY5G"

  tasks:

  - name: Display Gathered Facts
    debug:
      var: ansible_facts
      
  - name: Gather Azure Data
    include_tasks: tasks/get_azure_resources.yml

  - name: Update SNOW
    include_tasks: tasks/cmdb_add_or_update.yml
