---
- name: Add or Update CMDB CI - Host
  servicenow.itsm.configuration_item:
    instance: "{{snow_details}}"
    #sys_id: "{{ azure_host.sys_id }}"
    name: "{{ azure_host.name }}"
    short_description: "Azure Virtual Machine - {{azure_host.vm_size}}"
    serial_number: "{{ azure_host.id }}"
    #asset_tag: "{{ inv_entries.asset }}"
    sys_class_name: >-
          {%- if azure_host.os_type == 'Linux' -%}
          cmdb_ci_linux_server
          {%- elif azure_host.os_type == 'Windows' -%}
          cmdb_ci_win_server
          {%- else -%}
          cmdb_ci_server
          {%- endif -%}
    environment: "{{tags.environment | default('Environment Tag Missing')}}"
    category: Hardware
    ip_address: "Check Adapter Settings"
    other:
      discovery_source: "Azure through Ansible Automation"
      owned_by: "{{tags.owner | default('Owner Tag Missing')}}"
      supported_by: "JonnySykes IT Services LTD"
      host_name: "{{ azure_host.name }}"
      os_domain: "{{ azure_host.os_type }}"
      virtual: "true"
      location: "{{azure_host.location}}"
      cpu_core_count: "{{ all_machine_sizes.sizes | selectattr('name', '==', azure_host.vm_size) | map(attribute='number_of_cores') | first }}"
      cpu_count: ""
      ram: "{{ all_machine_sizes.sizes | selectattr('name', '==', azure_host.vm_size) | map(attribute='memory_in_mb') | first }}"
  register: host_data

  #- name: "Add Network Adapter for {{azure_host.name}}"
  #  include_tasks: tasks/cmdb_add_or_update_network_adapters.yml

  - name: Pring host_data
    debug:
      var: host_data