---
- name: Add or Update CMDB CI
  servicenow.itsm.configuration_item:
    instance: "{{snow_details}}"
    #sys_id: "{{ item.sys_id }}"
    name: "{{ item.name }}"
    short_description: "Azure Virtual Machine"
    serial_number: "{{ item.id }}"
    #asset_tag: "{{ inv_entries.asset }}"
    sys_class_name: cmdb_ci_server
    owned_by: "{{item.tags.owner | default('Owner Tag Missing')}}"
    environment: "{{item.tags.environment | default('Environment Tag Missing')}}"
    category: Hardware
    #sys_class_name: "{{ cmdb_table }}"
    ip_address: "{{ item.ip_address | default('IP Address Missing') }}"
#    other:
#      model_number: "{{ inv_entries.model }}"
#      manufacturer: "{{ inv_entries.mfg }}"
    supported_by: "JonnySykes IT Services LTD"
    discovery_source: "Azure through Ansible Automation"
  register: update_hw
