---
- name: Add or Update CMDB CI
  servicenow.itsm.configuration_item:
    instance: "{{snow_details}}"
    #sys_id: "{{ item.sys_id }}"
    name: "{{ inventory_hostname }}"
    short_description: "Azure Virtual Machine - {{virtual_machine_size}}"
    serial_number: "{{ vmid }}"
    #asset_tag: "{{ inv_entries.asset }}"
    sys_class_name: >-
          {%- if os_profile.system == 'Linux' -%}
          cmdb_ci_linux_server
          {%- elif os_profile.system == 'Windows' -%}
          cmdb_ci_win_server
          {%- else -%}
          cmdb_ci_server
          {%- endif -%}
    environment: "{{tags.environment | default('Environment Tag Missing')}}"
    category: Hardware
    ip_address: "{{ private_ipv4_addresses | default('IP Address Missing') }}"
    other:
      discovery_source: "Azure through Ansible Automation"
      owned_by: "{{tags.owner | default('Owner Tag Missing')}}"
      supported_by: "JonnySykes IT Services LTD"
      host_name: "{{ inventory_hostname }}"
      os_domain: "{{os_profile.system}}"
      virtual: "true"
      location: "{{location}}"
      cpu_core_count: "{{ all_machine_sizes.sizes | selectattr('name', '==', virtual_machine_size) | map(attribute='number_of_cores') | first }}"
      cpu_count: ""
      ram: "{{ all_machine_sizes.sizes | selectattr('name', '==', virtual_machine_size) | map(attribute='memory_in_mb') | first }}"
  register: update_hw
  delegate_to: localhost
