---
- name: Read Resources from Azure 
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{resource_group}}"
  register: all_azure_rg_resources

- name: Print Output
  ansible.builtin.debug:
    var: all_azure_rg_resources