---
- name: Get all VMs 
  azure.azcollection.azure_rm_virtualmachine_info:
    resource_group: "{{resource_group}}"    
  register: all_vms

- name: Get all virtual machine size Info
  azure.azcollection.azure_rm_virtualmachinesize_info:
    location: eastus
  register: all_machine_sizes

  